### ISSUE TITLE
Unhandled Exception when scrolling down

### ISSUE THREAD

**Issue by JyeGuru** [Parker147/Legends-Viewer#12]
Version: 1.13.09 (the one that comes with PeridexisErrant's r48 Pack)

To reproduce:
Find a page that has more than one screen of content
Scroll to the bottom, then scroll back up one notch of the scroll wheel
Scroll down as quickly as you can

Expected behavior:
Nothing, scrolling will stop at the bottom of the page

Actual behavior:
Exception is thrown (screenshot below) but can be continued past with seemingly no ill-effects.

![screenshot 2014-03-10 11 20 09](https://f.cloud.github.com/assets/5215014/2369810/380ebfea-a7eb-11e3-80d3-7566c950c5ed.png)

Notes:
This was most noticeable on entries with only one line or so below the bottom of the screen, they seem to always generate this message when I scroll down. Longer pages require the screen to be scrolled just up from the bottom before this happens.

**Comment by DocHoncho** [comment]
I can confirm this, it also will do it on the map views.

But of course, as with any good bug, I can't get it to do it right now.  I concur with @yukihyou, it appears to happen when there is text below a certain point and the scroll delta would go past the "EOF" for the entry.

The exception being an OverflowException implies that there's an unsigned type or an integer type too small for what it's being used for.  Either way, when you try to scroll down it's adding (or possibly subtracting) too much and triggering the Exception.

**Comment by JyeGuru** [comment]
Ok, so I sleuthed a little into the source code here an I think it's related to running an x64 OS. The use of .ToInt32() on line 106 in Controls/DwarfTabControl.cs seems to be the culprit. I'm not good enough with .Net to be able to suggest a fix, but I hope that this will help with a solution.

"OverflowException: On a 64-bit platform, the value of this instance is too large or too small to represent as a 32-bit signed integer." (Ref: http://msdn.microsoft.com/en-us/library/system.intptr.toint32(v=vs.110).aspx )

From my brief look on Google, it seems that using .ToInt64() should fix the issue (Ref: http://stackoverflow.com/questions/12390035/intptr-toint32-and-x64-systems ). I can't find anything that indicates there are issues using .ToInt64() on x86 systems, however the above link indicates issues using .ToInt32() on x64 systems.

Hope this helps.

**Comment by JyeGuru** [comment]
So, I bit the bullet and found a way to recompile my suggested change. Forked, changed, successful build is here: https://ci.appveyor.com/project/yukihyou/legends-viewer

This should allow download of the new exe, which runs without this error against my test data (just dropped it into the LNP folder over the original one). I did notice that there was a LOT more references to .ToInt32 in the code than just this one, but changing them all broke things. So - just made a single fix for this one.

Still needs to be tested on x86 platform to make sure it's not completely broken there though.

**Comment by PeridexisErrant** [comment]
Also fixes the problem for me on Windows 7 64-bit.  I suspect that there are also other changes between them though; notably the file selection window opens in the Dwarf Fortress folder instead of the same folder as the executable.

**Comment by JyeGuru** [comment]
Code is public in my repo, literally all I did was fork, change one line, recompile online though AppVeyor. I think the location of the file-open dialog is saved by Windows in this instance, as when doing my own testing it would show in the last folder used, regardless of which version (original or patched) I was running.

**Comment by DocHoncho** [comment]
The change to ToInt64 shouldn't be a problem for 32-bit systems, it simply converts to a long rather than an int.  The switch statement already has several cases cast to int, as well as some lovely magic numbers that have unknown meaning related to moving back/forward.

Honestly, the way this particular part of the code is written is very strange.  Although the exception occurs when processing a WM_MOUSEWHEEL event, the code in question doesn't actually handle the event, it seems primarily for the back/forward buttons.  Why those aren't handled by a regular message handler is beyond me.

**Comment by JyeGuru** [comment]
I don't pretend to fully understand the code, but it looks like it's grabbing all WindowProc messages related to the mouse[1] and finding the ones that relate specifically to those buttons with some magic numbers[2]. I'm not well versed enough to know if there's a better way, and this certainly does work, if inefficiently.

[1] http://wiki.winehq.org/List_Of_Windows_Messages
[2] http://social.msdn.microsoft.com/Forums/vstudio/en-US/c70d8083-e1a7-4a5e-8c46-f29be78c436e/mouseeventargs-in-webbrowser?forum=netfxbcl

(Interesting note: Searching google for _windowproc message "66059"_ comes up with this codebase higher than any other relevant references to this number)

**Comment by DocHoncho** [comment]
That was my conclusion as well.  The way wparam works in this context is
sufficiently weird to make determining the meaning of the numbers
impractical.  The high 16 bits encode the mouse wheel delta, the low a
bitmask for pressed buttons.

Good old Win32.

**Comment by Parker147** [comment]
Code was merged, seems to fix the issue.
