### ISSUE TITLE
It's unclear what the license for the code is

### ISSUE THREAD

**Issue by PeridexisErrant** [Parker147/Legends-Viewer#15]
From searching the Bay12 thread you don't seem to have any issues with other people using it, but a formal license makes a lot of people more comfortable.  

I just put a `license.txt` up on my stuff noting that I'm fine with it being used under the terms of the GPL3 or CC-BY-SA, since I like copyleft, but as long as it's clear it doesn't matter much.

**Comment by Parker147** [comment]
I agree. [Done.](https://github.com/Parker147/Legends-Viewer/commit/8983669147f84e39fac48a0200fa10108e2a214e)
